language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

before_script:
  - composer install --no-interaction
  - cp phpcs.dist.xml phpcs.xml

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
